name: Deploy to Strato (SFTP)

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:     ${{ secrets.SFTP_HOST }}       # ssh.strato.com
          port:       ${{ secrets.SFTP_PORT }}       # 22
          username:   ${{ secrets.SFTP_USERNAME }}   # bv. 570630717.swh.strato-hosting.eu
          password:   ${{ secrets.SFTP_PASSWORD }}   # masterwachtwoord
          local_path: "./"
          remote_path: "/httpdocs/"
          sftp_only: true
          exclude: |
            .git*
            .github/**
            node_modules/**
            **/.DS_Store
            **/Thumbs.db
            api/verkopen/**
            api/logs/**
            uploads/**
            tmp/**
